<?php

namespace Square\Inventory\Requests;

use Square\Core\Json\JsonSerializableType;
use Square\Core\Json\JsonProperty;
use Square\Types\InventoryAdjustment;

class UpdateInventoryAdjustmentRequest extends JsonSerializableType
{
    /**
     * A client-supplied, universally unique identifier (UUID) for the
     * request.
     *
     * See [Idempotency](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency) in the
     * [Build Basics](https://developer.squareup.com/docs/buildbasics) section for more
     * information.
     *
     * @var string $idempotencyKey
     */
    #[JsonProperty('idempotency_key')]
    private string $idempotencyKey;

    /**
     * Represents the updates being written to a past/existing inventory adjustment.
     * This works using sparse updates, meaning that any fields omitted from the inputted InventoryAdjustment
     * will retain their values.
     *
     * Only updates to the quantity, cost_money, vendor_id, and reason_id fields of an InventoryAdjustment can be made here.
     * Note that the quantity field must be provided, but it can be identical to the current quantity if there are no desired quantity changes.
     * cost_money and vendor_id can only be written to adjustments that add stock to the system (from_state of NONE or UNLINKED_RETURN) and to untracked sale adjustments.
     * reason_id can be changed to any reason that is valid for the adjustment's state transition. The reason of a system-generated adjustment (for example, SALE or RECOUNT) cannot be changed.
     * Adjustments generated by Square from other records cannot be updated. This includes inferred adjustments created by physical counts, transfer-like cross-location adjustments, and component adjustments.
     * Adjustments linked to purchase orders cannot be updated. Adjustments linked to sales can only have cost_money and vendor_id updated, and only for untracked sales.
     * Restock adjustments linked to an itemized return can have their quantity updated, up to the quantity remaining on the return.
     * Adjustments older than one year cannot be updated.
     *
     * @var InventoryAdjustment $adjustment
     */
    #[JsonProperty('adjustment')]
    private InventoryAdjustment $adjustment;

    /**
     * @param array{
     *   idempotencyKey: string,
     *   adjustment: InventoryAdjustment,
     * } $values
     */
    public function __construct(
        array $values,
    ) {
        $this->idempotencyKey = $values['idempotencyKey'];
        $this->adjustment = $values['adjustment'];
    }

    /**
     * @return string
     */
    public function getIdempotencyKey(): string
    {
        return $this->idempotencyKey;
    }

    /**
     * @param string $value
     */
    public function setIdempotencyKey(string $value): self
    {
        $this->idempotencyKey = $value;
        $this->_setField('idempotencyKey');
        return $this;
    }

    /**
     * @return InventoryAdjustment
     */
    public function getAdjustment(): InventoryAdjustment
    {
        return $this->adjustment;
    }

    /**
     * @param InventoryAdjustment $value
     */
    public function setAdjustment(InventoryAdjustment $value): self
    {
        $this->adjustment = $value;
        $this->_setField('adjustment');
        return $this;
    }
}
