<?php

namespace Square\Types;

use Square\Core\Json\JsonSerializableType;
use Square\Core\Json\JsonProperty;

class CardForgottenEventCard extends JsonSerializableType
{
    /**
     * @var ?string $id Unique ID for this card. Generated by Square.
     */
    #[JsonProperty('id')]
    private ?string $id;

    /**
     * @var ?string $customerId The ID of a customer created using the Customers API associated with the card.
     */
    #[JsonProperty('customer_id')]
    private ?string $customerId;

    /**
     * @var ?bool $enabled Indicates whether or not a card can be used for payments.
     */
    #[JsonProperty('enabled')]
    private ?bool $enabled;

    /**
     * An optional user-defined reference ID that associates this card with
     * another entity in an external system. For example, a customer ID from an
     * external customer management system.
     *
     * @var ?string $referenceId
     */
    #[JsonProperty('reference_id')]
    private ?string $referenceId;

    /**
     * Current version number of the card. Increments with each card update. Requests to update an
     * existing Card object will be rejected unless the version in the request matches the current
     * version for the Card.
     *
     * @var ?int $version
     */
    #[JsonProperty('version')]
    private ?int $version;

    /**
     * @var ?string $merchantId The ID of the merchant associated with the card.
     */
    #[JsonProperty('merchant_id')]
    private ?string $merchantId;

    /**
     * @param array{
     *   id?: ?string,
     *   customerId?: ?string,
     *   enabled?: ?bool,
     *   referenceId?: ?string,
     *   version?: ?int,
     *   merchantId?: ?string,
     * } $values
     */
    public function __construct(
        array $values = [],
    ) {
        $this->id = $values['id'] ?? null;
        $this->customerId = $values['customerId'] ?? null;
        $this->enabled = $values['enabled'] ?? null;
        $this->referenceId = $values['referenceId'] ?? null;
        $this->version = $values['version'] ?? null;
        $this->merchantId = $values['merchantId'] ?? null;
    }

    /**
     * @return ?string
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @param ?string $value
     */
    public function setId(?string $value = null): self
    {
        $this->id = $value;
        return $this;
    }

    /**
     * @return ?string
     */
    public function getCustomerId(): ?string
    {
        return $this->customerId;
    }

    /**
     * @param ?string $value
     */
    public function setCustomerId(?string $value = null): self
    {
        $this->customerId = $value;
        return $this;
    }

    /**
     * @return ?bool
     */
    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    /**
     * @param ?bool $value
     */
    public function setEnabled(?bool $value = null): self
    {
        $this->enabled = $value;
        return $this;
    }

    /**
     * @return ?string
     */
    public function getReferenceId(): ?string
    {
        return $this->referenceId;
    }

    /**
     * @param ?string $value
     */
    public function setReferenceId(?string $value = null): self
    {
        $this->referenceId = $value;
        return $this;
    }

    /**
     * @return ?int
     */
    public function getVersion(): ?int
    {
        return $this->version;
    }

    /**
     * @param ?int $value
     */
    public function setVersion(?int $value = null): self
    {
        $this->version = $value;
        return $this;
    }

    /**
     * @return ?string
     */
    public function getMerchantId(): ?string
    {
        return $this->merchantId;
    }

    /**
     * @param ?string $value
     */
    public function setMerchantId(?string $value = null): self
    {
        $this->merchantId = $value;
        return $this;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
