<?php

declare(strict_types=1);

namespace Square\Models;

class V1EmployeeRolePermissions
{
    public const REGISTER_ACCESS_SALES_HISTORY = 'REGISTER_ACCESS_SALES_HISTORY';

    public const REGISTER_APPLY_RESTRICTED_DISCOUNTS = 'REGISTER_APPLY_RESTRICTED_DISCOUNTS';

    public const REGISTER_CHANGE_SETTINGS = 'REGISTER_CHANGE_SETTINGS';

    public const REGISTER_EDIT_ITEM = 'REGISTER_EDIT_ITEM';

    public const REGISTER_ISSUE_REFUNDS = 'REGISTER_ISSUE_REFUNDS';

    public const REGISTER_OPEN_CASH_DRAWER_OUTSIDE_SALE = 'REGISTER_OPEN_CASH_DRAWER_OUTSIDE_SALE';

    public const REGISTER_VIEW_SUMMARY_REPORTS = 'REGISTER_VIEW_SUMMARY_REPORTS';
}
