<?php

declare(strict_types=1);

namespace Square\Models;

class V1MerchantBusinessType
{
    public const ACCOUNTING = 'ACCOUNTING';

    public const APPAREL_AND_ACCESSORY_SHOPS = 'APPAREL_AND_ACCESSORY_SHOPS';

    public const ART_DEALERS_GALLERIES = 'ART_DEALERS_GALLERIES';

    public const ART_DESIGN_AND_PHOTOGRAPHY = 'ART_DESIGN_AND_PHOTOGRAPHY';

    public const BAR_CLUB_LOUNGE = 'BAR_CLUB_LOUNGE';

    public const BEAUTY_AND_BARBER_SHOPS = 'BEAUTY_AND_BARBER_SHOPS';

    public const BOOK_STORES = 'BOOK_STORES';

    public const BUSINESS_SERVICES = 'BUSINESS_SERVICES';

    public const CATERING = 'CATERING';

    public const CHARITABLE_SOCIAL_SERVICE_ORGANIZATIONS = 'CHARITABLE_SOCIAL_SERVICE_ORGANIZATIONS';

    public const CHARITIBLE_ORGS = 'CHARITIBLE_ORGS';

    public const CLEANING_SERVICES = 'CLEANING_SERVICES';

    public const COMPUTER_EQUIPMENT_SOFTWARE_MAINTENANCE_REPAIR_SERVICES =
        'COMPUTER_EQUIPMENT_SOFTWARE_MAINTENANCE_REPAIR_SERVICES';

    public const CONSULTANT = 'CONSULTANT';

    public const CONTRACTORS = 'CONTRACTORS';

    public const DELIVERY_SERVICES = 'DELIVERY_SERVICES';

    public const DENTISTRY = 'DENTISTRY';

    public const EDUCATION = 'EDUCATION';

    public const FOOD_STORES_CONVENIENCE_STORES_AND_SPECIALTY_MARKETS =
        'FOOD_STORES_CONVENIENCE_STORES_AND_SPECIALTY_MARKETS';

    public const FOOD_TRUCK_CART = 'FOOD_TRUCK_CART';

    public const FURNITURE_HOME_AND_OFFICE_EQUIPMENT = 'FURNITURE_HOME_AND_OFFICE_EQUIPMENT';

    public const FURNITURE_HOME_GOODS = 'FURNITURE_HOME_GOODS';

    public const HOTELS_AND_LODGING = 'HOTELS_AND_LODGING';

    public const INDIVIDUAL_USE = 'INDIVIDUAL_USE';

    public const JEWELRY_AND_WATCHES = 'JEWELRY_AND_WATCHES';

    public const LANDSCAPING_AND_HORTICULTURAL_SERVICES = 'LANDSCAPING_AND_HORTICULTURAL_SERVICES';

    public const LANGUAGE_SCHOOLS = 'LANGUAGE_SCHOOLS';

    public const LEGAL_SERVICES = 'LEGAL_SERVICES';

    public const MEDICAL_PRACTITIONERS = 'MEDICAL_PRACTITIONERS';

    public const MEDICAL_SERVICES_AND_HEALTH_PRACTITIONERS = 'MEDICAL_SERVICES_AND_HEALTH_PRACTITIONERS';

    public const MEMBERSHIP_ORGANIZATIONS = 'MEMBERSHIP_ORGANIZATIONS';

    public const MUSIC_AND_ENTERTAINMENT = 'MUSIC_AND_ENTERTAINMENT';

    public const OTHER = 'OTHER';

    public const OUTDOOR_MARKETS = 'OUTDOOR_MARKETS';

    public const PERSONAL_SERVICES = 'PERSONAL_SERVICES';

    public const POLITICAL_ORGANIZATIONS = 'POLITICAL_ORGANIZATIONS';

    public const PROFESSIONAL_SERVICES = 'PROFESSIONAL_SERVICES';

    public const REAL_ESTATE = 'REAL_ESTATE';

    public const RECREATION_SERVICES = 'RECREATION_SERVICES';

    public const REPAIR_SHOPS_AND_RELATED_SERVICES = 'REPAIR_SHOPS_AND_RELATED_SERVICES';

    public const RESTAURANTS = 'RESTAURANTS';

    public const RETAIL_SHOPS = 'RETAIL_SHOPS';

    public const SCHOOLS_AND_EDUCATIONAL_SERVICES = 'SCHOOLS_AND_EDUCATIONAL_SERVICES';

    public const SPORTING_GOODS = 'SPORTING_GOODS';

    public const TAXICABS_AND_LIMOUSINES = 'TAXICABS_AND_LIMOUSINES';

    public const TICKET_SALES = 'TICKET_SALES';

    public const TOURISM = 'TOURISM';

    public const TRAVEL_TOURISM = 'TRAVEL_TOURISM';

    public const VETERINARY_SERVICES = 'VETERINARY_SERVICES';

    public const WEB_DEV_DESIGN = 'WEB_DEV_DESIGN';
}
